[versions]
agp = "8.13.1"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
room = "2.6.1"
firebaseBom = "33.7.0"
mpandroidchart = "3.1.0"
lifecycle = "2.8.7"
navigation = "2.8.5"
gson = "2.10.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
extJunit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
roomRuntime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
roomCompiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
roomKtx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
firebaseBom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebaseAuth = { group = "com.google.firebase", name = "firebase-auth" }
firebaseFirestore = { group = "com.google.firebase", name = "firebase-firestore" }
firebaseStorage = { group = "com.google.firebase", name = "firebase-storage" }
mpandroidchart = { group = "com.github.PhilJay", name = "MPAndroidChart", version.ref = "mpandroidchart" }
lifecycleViewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycle" }
lifecycleLivedata = { group = "androidx.lifecycle", name = "lifecycle-livedata", version.ref = "lifecycle" }
navigationFragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigation" }
navigationUi = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigation" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
googleServices = { id = "com.google.gms.google-services", version = "4.4.0" }
